source 'https://rubygems.org'

ruby '2.2.2'

gem 'rails', '4.2.1'

gem 'rails-api'

group :development, :test do
  gem 'spring'
  gem 'rubocop'
  gem 'brakeman'
  gem 'rubocop-checkstyle_formatter'
  gem 'rspec-rails', '~> 3.0'
  gem 'database_cleaner', '~> 1.3.0'
  gem 'factory_girl_rails', '~> 4.0'
  gem 'shoulda-matchers'
  gem 'pry'
end

gem 'puma'

gem 'pg', '~> 0.18.2'

# To use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Deploy with Capistrano
# gem 'capistrano', :group => :development

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'

gem 'dotenv-rails'

gem 'rest-client'
gem 'acts-as-taggable-on'

# Documentation
gem 'apipie-rails', '~> 0.2.6'

# CORS
gem 'rack-cors'
